server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8

gril:
  cupSize: F
  age: 18

commont: "cupSize:${gril.cupSize},age:${gril.age}"

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true